# Generated by Django 5.2.4 on 2025-08-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('HIIT', 'HIIT')], max_length=50)),
                ('date', models.DateField()),
                ('instructor', models.CharField(max_length=50)),
                ('available_slots', models.PositiveIntegerField()),
            ],
        ),
    ]
