# Generated by Django 5.2.4 on 2025-08-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
