# Generated by Django 5.2.4 on 2025-08-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0003_alter_fitness_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
